# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Set plugins
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme

# Site settings
encoding: utf-8 # Make sure the encoding is right
#lang: ko # Set the site language

url: 'https://quark325.github.io/'
baseurl: ''
title: 'My website'
description: 'This is my new website'
permalink: pretty
logo: '/images/name_georgia.png'
google_analytics: 'G-57VBVBVWBS'

# Pagination
paginate: 5
paginate_path: page:num

# Header nav
navigation_header:
  - title: Posts
    url: /
  - title: Categories
    url: /categories/
  - title: Search
    url: /search/

# Footer nav
navigation_footer:
  - title: Back to top
    url: '#top'

# Collections
collections:
  posts:
    title: Posts
    output: true
    # description: 'My thoughts and ideas'
    # feature_text: |
    #   # Welcome to my blog
    feature_image: '/images/about.jpeg'

# Collection settings
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: post # Set the default layout for posts
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: page # Set the default layout for pages

# sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
#   Twitter: '#0d94e7'
#   facebook: '#3B5998'
#   Email: true
